### PR TITLE
Added thanks page after confirming booking

### PR DESCRIPTION
**Pull request by erikwessman**
Co-Authored-By: Elias Hallberg <54537680+Elias-Hallberg@users.noreply.github.com>

### CODE REVIEW

**Comment by Elias-Hallberg** [comment]
Bästa bransh jag sett

**Review by elias-carlson — APPROVED** [review]
Ser bra ut!

**Review by ArvidHolmqvist — APPROVED** [review]
🤔

**Review by idalinnakallio — APPROVED** [review]
häftigt!!!

**Pull request merged**
