### PR TITLE
Initial code environment added

### PR DESCRIPTION
**Pull request by elias-carlson**
Ida, Elias, Elias, Arvid, Lisa

### CODE REVIEW

**Review by Elias-Hallberg — COMMENTED** [review]
it is bad, pls redo

**Review by ArvidHolmqvist — APPROVED** [review]
WOW! 💯 🔥

**Review by idalinnakallio — APPROVED** [review]
Nice and easy!

**Comment by elias-carlson** [comment]
> it is bad, pls redo

no

**Review by lisamattus — APPROVED** [review]
nice!

**Comment by Elias-Hallberg** [comment]
> > it is bad, pls redo
> 
> no

pls :(

**Pull request merged**
