### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by elias-carlson**
Removed files that we don't need, and added .vscode to .gitignore

### CODE REVIEW

**Review by erikwessman — APPROVED** [review]
i approve

**Comment by elias-carlson** [comment]
> i approve

tysm, kind sir 🥺

**Review by Elias-Hallberg — APPROVED** [review]
here you have an approve good sir

**Review by ArvidHolmqvist — APPROVED** [review]

**Review by astridolaus — APPROVED** [review]

**Review by lisamattus — APPROVED** [review]
wow blev jätterent<:)

**Pull request merged**
